import type { MetadataRoute } from "next";

/**
 * PWA manifest so the app can be installed to the home screen and run
 * fullscreen/standalone on all devices. Icons are the same heart as the header
 * (generated by npm run generate-favicons).
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Family Planner",
    short_name: "Family Planner",
    description: "A simple and beautiful family week planner",
    start_url: "/",
    display: "standalone",
    orientation: "any",
    background_color: "#ffffff",
    theme_color: "#ec4899",
    categories: ["productivity", "lifestyle"],
    icons: [
      {
        src: "/icons/icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "maskable",
      },
      {
        src: "/icons/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
